netbooksci/estudiantes/urls.py
from django.urls import include, path, re_path

from . import views
app_name = "estudiantes"

urlpatterns = [
				path('', views.index, name='index'),
				path('listaestudiante', views.ListaEstudiantes.as_view(), name='lista_estudiante'),
				path('nuevoestudiante', views.NuevoEstudiante.as_view(), name='nuevo_estudiante'),
				#el re_path lo saqué de esta documentación oficial https://docs.djangoproject.com/en/3.0/topics/http/urls/
				#re_path(r'^editarestudiante/(?P<id_estudiante>\d+)/$', views.editarestudiante, name='editar_estudiante'),
				re_path(r'^editarestudiante/(?P<pk>\d+)/$', views.EditarEstudiante.as_view(), name='editar_estudiante'),
				#re_path(r'^eliminarestudiante/(?P<pk>\d+)/$', views.EliminarEstudiante.as_view(), name='eliminar_estudiante'),
				#re_path(r'^eliminarestudiante/(?P<id_estudiante>\d+)/$', views.eliminarestudiante, name='eliminar_estudiante'),
				re_path(r'^eliminarestudiante/(?P<pk>\d+)/$', views.BorrarEstudiante.as_view(), name='eliminar_estudiante'),

]

netbooksci/netbooksci/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('padron/', include('padron.urls', namespace = "padron_nets")),
    path('admin/', admin.site.urls),
    path('estudiantes/', include('estudiantes.urls', namespace = "estudiantes")),
    #Acá defino que la página por defecto al ingresar a localhost:8000 sea el
    #index de padrón
    path('', include('padron.urls', namespace = "home")),
]

netbooksci/padron/urls.py
from django.urls import include, path, re_path

from . import views

app_name = "padron_nets"
urlpatterns = [
				path('', views.index, name='index'),
				path('listacomputadoras', views.ListaNets.as_view(), name='lista_nets'),
				path('nuevacomputadora', views.NuevaNet.as_view(), name='nueva_net'),
				#el re_path lo saqué de esta documentación oficial https://docs.djangoproject.com/en/3.0/topics/http/urls/
				re_path(r'^editarnet/(?P<pk>\d+)/$', views.EditarNet.as_view(), name='editar_net'),
				re_path(r'^eliminarnet/(?P<pk>\d+)/$', views.BorrarNet.as_view(), name='eliminar_net'),
]

netbooksci/padron/models.py
from django.db import models
from estudiantes.models import Estudiante

class Computadora(models.Model):

	estudiante = models.OneToOneField(Estudiante, null=True, blank=True, on_delete=models.CASCADE)
	serie = models.CharField(max_length=20)
	idhardware = models.CharField(max_length=20)
	observacion = models.TextField()

	def __str__(self):
		return self.serie

netbooksci/padron/forms.py
from django import forms

from padron.models import Computadora
class ComputadoraForm (forms.ModelForm):
    class Meta:
        model = Computadora

        fields = [
        'estudiante',
        'serie',
        'idhardware',
        'observacion',
        ]

        labels = {
        'estudiante':'Estudiante',
        'serie' : 'N° de Serie',
        'idhardware':'ID de Hardware',
        'observacion':'Observaciones',
         }

        widgets = {
         'estudiante' :forms.Select(attrs={'class':'form-control'}),
         'serie': forms.TextInput(attrs={'class':'form-control'}),
         'idhardware' : forms.TextInput(attrs={'class':'form-control'}),
         'observacion' : forms.TextInput(attrs={'class':'form-control'}),
         }

netbooksci/padron/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from padron.models import Computadora
#Importo el formulario para crear nuevos estudiantes
from padron.forms import ComputadoraForm

# Create your views here.

def index(request):
	return render(request, 'padron/index.html')

"""def nuevacomputadora (request):
	if request.method=='POST':
		form = ComputadoraForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect ('padron_nets:index')
	else:
		form = ComputadoraForm()

	return render(request, 'padron/nuevacomputadora.html', {'form':form})"""


class ListaNets (ListView):
	model = Computadora
	template_name = 'padron/listanets.html'

class NuevaNet (CreateView):
	model = Computadora
	form_class = ComputadoraForm
	template_name = 'padron/nuevacomputadora.html'
	success_url = reverse_lazy('padron_nets:lista_nets')

class EditarNet (UpdateView):
	model = Computadora
	form_class = ComputadoraForm
	template_name = 'padron/nuevacomputadora.html'
	success_url = reverse_lazy('padron_nets:lista_nets')

class BorrarNet (DeleteView):
	model = Computadora
	template_name = 'padron/eliminarnet.html'
	success_url = reverse_lazy('padron_nets:lista_nets')

netbooksci/templates/padron/eliminarnet.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar la computadora {{ object.idhardware }}, serie: {{ object.serie }}?</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'padron_nets:lista_nets' %}">Cancelar</a>
</form>

{% endblock %}

netbooksci/templates/padron/index.html
{% extends 'base/base.html' %}
{% block encabezado %}
<h4>Sistema DHC-CI</h4>
{% endblock %}
{% block contenido %}

{% load static %}
<div class="row">
  <div class="col-sm-3">
    <div class="card" style="width:400px">
        <img class="card-img-top" src="{% static 'img/estudiantes.jpg' %}" alt="Card image" style="height:300px">
        <div class="card-body">
          <h4 class="card-title">Carga de alumnxs</h4>
          <p class="card-text">Aquí podrá dar de alta alumnxs</p>
          <a href="{% url 'estudiantes:nuevo_estudiante' %}" class="btn btn-primary stretched-link">Ingresar</a>
        </div>
    </div>
  </div>


    <div class="col-sm-3">
      <div class="card" style="width:400px">
          <img class="card-img-top" src="{% static 'img/estudiantes.jpg' %}" alt="Card image" style="height:300px">
          <div class="card-body">
            <h4 class="card-title">Listado de alumnos</h4>
            <p class="card-text">Aquí podrá ver los alumnxs cargados, editarlos y borrarlos</p>
            <a href="{% url 'estudiantes:lista_estudiante' %}" class="btn btn-primary stretched-link">Ingresar</a>
          </div>
      </div>
    </div>


  <div class="col-sm-3">
    <div class="card" style="width:400px">
        <img class="card-img-top" src="{% static 'img/netbooks.png' %}" alt="Card image" style="height:300px">
        <div class="card-body">
          <h4 class="card-title">Carga de equipos</h4>
          <p class="card-text">Aquí podrá dar de alta equipos</p>
          <a href="{% url 'padron_nets:nueva_net' %}" class="btn btn-primary stretched-link">Ingresar</a>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
    <div class="card" style="width:400px">
        <img class="card-img-top" src="{% static 'img/netbooks.png' %}" alt="Card image" style="height:300px">
        <div class="card-body">
          <h4 class="card-title">Listado de equipos</h4>
          <p class="card-text">Aquí podrá ver el listado de computadoras registradas</p>
          <a href="{% url 'padron_nets:lista_nets' %}" class="btn btn-primary stretched-link">Ingresar</a>
        </div>
    </div>
  </div>
</div>





{% endblock %}

netbooksci/templates/padron/listanets.html
{%  extends 'base/base.html' %}

{% block contenido %}

<table class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>Apellido</td>
      <td>Nombre</td>
      <td>Serie</td>
      <td>Hardware ID</td>
      <td>Observaciones</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de nets para mostrar-->
    {% if object_list %}
      {% for netbook in object_list %}
        <tr>
          <td>{{netbook.id}}</td>
          <td>{{netbook.estudiante.apellido}}</td>
          <td>{{netbook.estudiante.nombre}}</td>
          <td>{{netbook.serie}}</td>
          <td>{{netbook.idhardware}}</td>
          <td>{{netbook.observacion}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
               <a class="dropdown-item" href="{% url 'padron_nets:editar_net' netbook.id %}">Editar</a>
               <a class="dropdown-item" href="{% url 'padron_nets:eliminar_net' netbook.id %}">Eliminar</a>
             </div>
          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay computadoras registradas en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'padron_nets:nueva_net' %}">Agregar computadora</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}

netbooksci/templates/padron/nuevacomputadora.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de computadoras</h3>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-outline-success" name="button">Guardar computadora</button>
</form>
{% endblock %}