netbooksci/estudiantes/urls.py
from django.urls import include, path, re_path

from . import views
app_name = "estudiantes"

urlpatterns = [
				path('', views.index, name='index'),
				path('listaestudiante', views.ListaEstudiantes.as_view(), name='lista_estudiante'),
				path('nuevoestudiante', views.NuevoEstudiante.as_view(), name='nuevo_estudiante'),
				#el re_path lo saqué de esta documentación oficial https://docs.djangoproject.com/en/3.0/topics/http/urls/
				#re_path(r'^editarestudiante/(?P<id_estudiante>\d+)/$', views.editarestudiante, name='editar_estudiante'),
				re_path(r'^editarestudiante/(?P<pk>\d+)/$', views.EditarEstudiante.as_view(), name='editar_estudiante'),
				#re_path(r'^eliminarestudiante/(?P<pk>\d+)/$', views.EliminarEstudiante.as_view(), name='eliminar_estudiante'),
				#re_path(r'^eliminarestudiante/(?P<id_estudiante>\d+)/$', views.eliminarestudiante, name='eliminar_estudiante'),
				re_path(r'^eliminarestudiante/(?P<pk>\d+)/$', views.BorrarEstudiante.as_view(), name='eliminar_estudiante'),

]

netbooksci/netbooksci/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('padron/', include('padron.urls', namespace = "padron_nets")),
    path('admin/', admin.site.urls),
    path('estudiantes/', include('estudiantes.urls', namespace = "estudiantes")),
    #Acá defino que la página por defecto al ingresar a localhost:8000 sea el
    #index de padrón
    path('', include('padron.urls', namespace = "home")),
]

netbooksci/padron/urls.py
from django.urls import include, path, re_path

from . import views

app_name = "padron_nets"
urlpatterns = [
				path('', views.index, name='index'),
				path('listacomputadoras', views.ListaNets.as_view(), name='lista_nets'),
				path('nuevacomputadora', views.NuevaNet.as_view(), name='nueva_net'),
				#el re_path lo saqué de esta documentación oficial https://docs.djangoproject.com/en/3.0/topics/http/urls/
				re_path(r'^editarnet/(?P<pk>\d+)/$', views.EditarNet.as_view(), name='editar_net'),
				re_path(r'^eliminarnet/(?P<pk>\d+)/$', views.BorrarNet.as_view(), name='eliminar_net'),
]

netbooksci/estudiantes/models.py
from django.db import models

#Creo el modelo de estudiante

class Estudiante (models.Model):

	#defino los cursos
	#se sigue la estructura año-división (aXdX)
	a1d1 = 'a1d1'
	a1d2 = 'a1d2'
	a1d3 = 'a1d3'
	a1d4 = 'a1d4'
	a1d5 = 'a1d5'
	a2d1 = 'a2d1'
	a2d2 = 'a2d2'
	a2d3 = 'a2d3'
	a2d4 = 'a2d4'
	a2d5 = 'a2d5'
	a3d1 = 'a3d1'
	a3d2 = 'a3d2'
	a3d3 = 'a3d3'
	a3d4 = 'a3d4'
	a3d5 = 'a3d5'

	a4dnat1 = 'a4dnat1'
	a4dnat2 = 'a4dnat2'
	a5dnat1 = 'a5dnat1'
	a5dnat2 = 'a5dnat2'
	a6dnat = 'a6dnat'

	a4dc = 'a4dc'
	a5dc = 'a5dc'
	a6dc = 'a6dc'

	a4dt = 'a4dt'
	a5dt = 'a5dt'
	a6dt = 'a6dt'

	a4dh = 'a4dh'
	a5dh = 'a5dh'
	a6dh = 'a6dh'

	egre = 'egre'

	denominacion_cursos = [
		(a1d1,'1° Año 1a. División'),
		(a1d2,'1° Año 2a. División'),
		(a1d3,'1° Año 3a. División'),
		(a1d4,'1° Año 4a. División'),
		(a1d5,'1° Año 5a. División'),
		(a2d1,'2° Año 1a. División'),
		(a2d2,'2° Año 2a. División'),
		(a2d3,'2° Año 3a. División'),
		(a2d4,'2° Año 4a. División'),
		(a2d5,'2° Año 5a. División'),
		(a3d1,'3° Año 1a. División'),
		(a3d2,'3° Año 2a. División'),
		(a3d3,'3° Año 3a. División'),
		(a3d4,'3° Año 4a. División'),
		(a3d5,'3° Año 5a. División'),
		(a4dnat1,'4° Año Naturales 1° División'),
		(a4dnat2,'4° Año Naturales 2° División'),
		(a5dnat1,'5° Año Naturales 1° División'),
		(a5dnat2,'5° Año Naturales 2° División'),
		(a6dnat,'6° Año Naturales'),
		(a4dc,'4° Año Comunicación'),
		(a5dc,'5° Año Comunicación'),
		(a6dc,'6° Año Comunicación'),
		(a4dt,'4° Año Turismo'),
		(a5dt,'5° Año Turismo'),
		(a6dt,'6° Año Turismo'),
		(a4dh,'4° Año Humanidades'),
		(a5dh,'5° Año Humanidades'),
		(a6dh,'6° Año Humanidades'),
		(egre,'EGRESADO'),
	]

	apellido = models.CharField(max_length=60)
	nombre = models.CharField(max_length=150)
	curso = models.CharField(max_length=10, choices=denominacion_cursos, default=a1d1)
	dni = models.IntegerField()
	email = models.EmailField()
	fono = models.CharField(max_length=20)

	def __str__(self):
		return self.apellido + ", " + self.nombre

netbooksci/estudiantes/forms.py
from django import forms

from estudiantes.models import Estudiante
class EstudianteForm (forms.ModelForm):
    class Meta:
        model = Estudiante

        fields = [
        'apellido',
        'nombre',
        'curso',
        'dni',
        'email',
        'fono',
        ]

        labels = {
        'apellido':'Apellido',
        'nombre' : 'Nombres',
        'curso':'Curso actual',
        'dni':'N° DNI',
        'email':'Correo electrónico',
        'fono':'Teléfono de contacto',
         }

        widgets = {
         'apellido':forms.TextInput(attrs={'class':'form-control'}),
         'nombre': forms.TextInput(attrs={'class':'form-control'}),
         'curso' : forms.Select(attrs={'class':'form-control'}),
         'dni' : forms.TextInput(attrs={'class':'form-control'}),
         'email' : forms.TextInput(attrs={'class':'form-control'}),
         'fono' : forms.TextInput(attrs={'class':'form-control'}),
         }

netbooksci/estudiantes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
#Importo el formulario para crear nuevos estudiantes
from estudiantes.forms import EstudianteForm


#Importo el modelo Estudiante

from estudiantes.models import Estudiante
# Create your views here.

def index(request):
	return render(request, 'estudiantes/index.html')

"""def nuevoestudiante (request):
	if request.method=='POST':
		form = EstudianteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect ('estudiantes:index')
	else:
		form = EstudianteForm()

	return render(request, 'estudiantes/nuevoestudiante.html', {'form':form})"""


#La función listaestudiante fue para probar crear la vista usando funciones
#Queda sin uso porque después empecé a usar herencia de ListView

"""	def listaestudiante (request):
		estudiante = Estudiante.objects.all().order_by('apellido')
		#Acá creo un diccionario que llamaré 'estudiantes', así que
		#en la template preguntaré por 'estudianteS' y NO 'estudiantE'
		conjunto = {'estudiantes':estudiante}

		#El conjunto lo envío como contexto al template
		return render (request, 'estudiantes/listaestudiante.html', conjunto)"""

"""def editarestudiante (request, id_estudiante):
	estudiante = Estudiante.objects.get(id=id_estudiante)
	if request.method =='GET':
		form = EstudianteForm(instance=estudiante)
	else:
		form = EstudianteForm(request.POST, instance=estudiante)
		if form.is_valid():
			form.save()
		return redirect('estudiantes:lista_estudiante')
	return render(request, 'estudiantes/nuevoestudiante.html', {'form':form})"""

"""def eliminarestudiante(request, id_estudiante):
	estudiante = Estudiante.objects.get(id=id_estudiante)
	if request.method == 'POST':
		estudiante.delete()
		return redirect ('estudiantes:lista_estudiante')
	return render(request, 'estudiantes/eliminarestudiante.html', {'estudiante':estudiante})"""

class ListaEstudiantes (ListView):
	model = Estudiante
	template_name = 'estudiantes/listaestudiante.html'

class NuevoEstudiante (CreateView):
	model = Estudiante
	form_class = EstudianteForm
	template_name = 'estudiantes/nuevoestudiante.html'
	success_url = reverse_lazy('estudiantes:lista_estudiante')

class EditarEstudiante (UpdateView):
	model = Estudiante
	form_class = EstudianteForm
	template_name = 'estudiantes/nuevoestudiante.html'
	success_url = reverse_lazy('estudiantes:lista_estudiante')

class BorrarEstudiante (DeleteView):
	model = Estudiante
	template_name = 'estudiantes/eliminarestudiante.html'
	success_url = reverse_lazy('estudiantes:lista_estudiante')

netbooksci/templates/estudiantes/eliminarestudiante.html
{% extends 'base/base.html' %}

{% block contenido %}
<form method="post">
  {% csrf_token %}
  <h3>¿Desea eliminar el estudiante {{ object.apellido }}, {{ object.nombre }}</h3>
  <button class= "btn btn-danger" type="submit" name="button">Eliminar</button>
  <a class= "btn btn-primary" href="{% url 'estudiantes:lista_estudiante' %}">Cancelar</a>
</form>

{% endblock %}

netbooksci/templates/estudiantes/index.html
{% extends 'base/base.html' %}

{% block encabezado %}
<h4>Este Index no cumple ninguna función :)</h4>
{% endblock %}

netbooksci/templates/estudiantes/listaestudiante.html
{%  extends 'base/base.html' %}

{% block contenido %}

<table class='table table-striped'>
  <thead>
    <tr>
      <td>#</td>
      <td>apellido</td>
      <td>Nombre</td>
      <td>Curso</td>
      <td>DNI</td>
      <td>Correo Electrónico</td>
      <td>Teléfono</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <!-- Veo si hay registros de estudiantes para mostrar-->
    {% if object_list %}
      {% for estudiante in object_list %}
        <tr>
          <td>{{estudiante.id}}</td>
          <td>{{estudiante.apellido}}</td>
          <td>{{estudiante.nombre}}</td>
          <td>{{estudiante.curso}}</td>
          <td>{{estudiante.dni}}</td>
          <td>{{estudiante.email}}</td>
          <td>{{estudiante.fono}}</td>
          <td>
            <div class="dropdown">
             <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
               Acciones
             </button>
             <div class="dropdown-menu">
               <a class="dropdown-item" href="{% url 'estudiantes:editar_estudiante' estudiante.id %}">Editar</a>
               <a class="dropdown-item" href="{% url 'estudiantes:eliminar_estudiante' estudiante.id %}">Eliminar</a>
             </div>
          </div>
          </td>
        </tr>
      {% endfor %}
    {% else %}
    <h1>No hay estudiantes registrados en el sistema</h1>
    <a class="btn btn-outline-success" href="{% url 'estudiantes:nuevo_estudiante' %}">Agregar estudiante</a>
    {% endif %}
  </tbody>
</table>

{% endblock %}

netbooksci/templates/estudiantes/nuevoestudiante.html
{% extends 'base/base.html'  %}

{% block contenido %}
<h3>Carga de estudiantes</h3>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-outline-success" name="button">Guardar estudiante</button>
</form>
{% endblock %}