netbooksci/netbooksci/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('padron/', include('padron.urls', namespace = "padron_nets")),
    path('admin/', admin.site.urls),
    path('estudiantes/', include('estudiantes.urls', namespace = "estudiantes")),
    #Acá defino que la página por defecto al ingresar a localhost:8000 sea el
    #index de padrón
    path('', include('padron.urls', namespace = "home")),
]

netbooksci/padron/urls.py
from django.urls import include, path, re_path

from . import views

app_name = "padron_nets"
urlpatterns = [
				path('', views.index, name='index'),
				path('listacomputadoras', views.ListaNets.as_view(), name='lista_nets'),
				path('nuevacomputadora', views.NuevaNet.as_view(), name='nueva_net'),
				#el re_path lo saqué de esta documentación oficial https://docs.djangoproject.com/en/3.0/topics/http/urls/
				re_path(r'^editarnet/(?P<pk>\d+)/$', views.EditarNet.as_view(), name='editar_net'),
				re_path(r'^eliminarnet/(?P<pk>\d+)/$', views.BorrarNet.as_view(), name='eliminar_net'),
]

netbooksci/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title> {% block title %} Sistema DHC-CI {% endblock %}</title>

    {# Cargo Bootstrap #}
    {% load bootstrap4 %}
    {# CSS Bootstrap #}
    {% bootstrap_css %}
  </head>
  <body>
    <div class="container">

      {% block encabezado %}
      <h4>Sistema DHC-CI</h4>
      <a href="{% url 'padron_nets:index' %}" class="btn btn-outline-primary" role="button">Ir al menú inicial</a>
      {% endblock %}

      {% block contenido %}
      <h5>Este es el contenido del archivo base</h5>
      {% endblock %}


      {% block pie %}
      <footer>
        <p>Sistema para el registro interno de netbooks DHC-CI</p>
      </footer>
      {% endblock %}

    </div>
      <!-- JS y JQuery para BS -->
      {# JS y jQuery Bootstrap #}
      {% bootstrap_javascript jquery='full' %}
  </body>
</html>